<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('orders')->insert([
            [
                'name' => 'Budi Santoso',
                'institution' => 'Universitas Palawi',
                'position' => 'Dosen',
                'participants_count' => 10,
                'address' => 'Jl. Raya Palawi No. 123',
                'phone_number' => '081234567890',
                'user_id' => 1,
                'rooms_count' => 2,
                'price' => 1000000,
                'days_count' => 2,
                'check_in' => Carbon::now(),
                'check_out' => Carbon::now()->addDays(2),
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Siti Rahma',
                'institution' => 'PT Palawi Indah',
                'position' => 'Manager',
                'participants_count' => 5,
                'address' => 'Jl. Merdeka No. 45',
                'phone_number' => '082233445566',
                'user_id' => 1,
                'rooms_count' => 3,
                'price' => 1500000,
                'days_count' => 3,
                'check_in' => Carbon::now()->addDays(2),
                'check_out' => Carbon::now()->addDays(5),
                'status' => 'confirmed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Andi Pratama',
                'institution' => 'SMK Palawi',
                'position' => 'Guru',
                'participants_count' => 20,
                'address' => 'Jl. Pendidikan No. 10',
                'phone_number' => '087777777777',
                'user_id' => 1,
                'rooms_count' => 2,
                'price' => 1200000,
                'days_count' => 2,
                'check_in' => Carbon::now()->addDays(3),
                'check_out' => Carbon::now()->addDays(5),
                'status' => 'confirmed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rina Marlina',
                'institution' => 'CV Maju Bersama',
                'position' => 'Supervisor',
                'participants_count' => 8,
                'address' => 'Jl. Ahmad Yani No. 77',
                'phone_number' => '085611223344',
                'user_id' => 1,
                'rooms_count' => 3,
                'price' => 950000,
                'days_count' => 2,
                'check_in' => Carbon::now()->addDays(4),
                'check_out' => Carbon::now()->addDays(6),
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Joko Widodo',
                'institution' => 'PT Jaya Abadi',
                'position' => 'Direktur',
                'participants_count' => 12,
                'address' => 'Jl. Soekarno Hatta No. 55',
                'phone_number' => '081233344455',
                'user_id' => 1,
                'rooms_count' => 3,
                'price' => 2000000,
                'days_count' => 3,
                'check_in' => Carbon::now()->addDays(5),
                'check_out' => Carbon::now()->addDays(8),
                'status' => 'confirmed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lina Kartika',
                'institution' => 'Universitas Negeri Palawi',
                'position' => 'Mahasiswa',
                'participants_count' => 4,
                'address' => 'Jl. Pendidikan No. 88',
                'phone_number' => '082111223344',
                'user_id' => 1,
                'rooms_count' => 1,
                'price' => 500000,
                'days_count' => 2,
                'check_in' => Carbon::now()->addDays(6),
                'check_out' => Carbon::now()->addDays(8),
                'status' => 'checked_in',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tono Hidayat',
                'institution' => 'Koperasi Sejahtera',
                'position' => 'Bendahara',
                'participants_count' => 6,
                'address' => 'Jl. Cendrawasih No. 9',
                'phone_number' => '081211223344',
                'user_id' => 1,
                'rooms_count' => 2,
                'price' => 1100000,
                'days_count' => 2,
                'check_in' => Carbon::now()->addDays(7),
                'check_out' => Carbon::now()->addDays(9),
                'status' => 'cancelled',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Agus Salim',
                'institution' => 'SMAN 1 Palawi',
                'position' => 'Kepala Sekolah',
                'participants_count' => 15,
                'address' => 'Jl. Pendidikan No. 100',
                'phone_number' => '085211223344',
                'user_id' => 1,
                'rooms_count' => 4,
                'price' => 2500000,
                'days_count' => 3,
                'check_in' => Carbon::now()->addDays(8),
                'check_out' => Carbon::now()->addDays(11),
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
